# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            bases=(models.Model, employees.models.ModelNames),
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('dev', 'Developer'), ('test', 'Tester'), ('adm', 'Administrator')], max_length=20)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, employees.models.ModelNames),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Profession'),
        ),
    ]
